// import Navbar from "@/components/global/Navbar";
import "./globals.css";
import Footer from "../components/global/Footer";
import RegisterModal from "../components/global/RegisterModal";

export const metadata = {
  title: "Impact IT services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="">
        {children}
        <Footer />
        {/* <Footer2 /> */}
        <RegisterModal />
      </body>
    </html>
  );
}
